### ISSUE TITLE
Pasar página de "about" a app website

### ISSUE THREAD

**Issue by fabianabarca** [fabianabarca/ferias#10]
Colocar la página "about" (y cambiarle el nombre a about.html y `/acerca`) dentro de `website` y también otras páginas misceláneas: 

- `acerca`: información sobre TC-691 "Tropicalización de la tecnología" e información técnica sobre el sitio web (OpenStreetMap, tecnologías web, etc.)
- `contacto`: información de contacto del TCU y de cada feria

**Comment by Sirlany-Lany** [comment]
Concluido
